version: '3.8'

services:
  mysql:
    image: mysql:lts
    container_name: camp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
